[package]
name = "investment_returns_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.57", features = ["derive"] }
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
